[
    {
        "cve": "CVE-2022-35411",
        "poc_github": true,
        "full_name": "fuzzlove/CVE-2022-35411",
        "owner_login": "fuzzlove",
        "owner_id": 44779781,
        "owner_html_url": "https://github.com/fuzzlove",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/44779781?v=4",
        "html_url": "https://github.com/fuzzlove/CVE-2022-35411",
        "description": "rpc.py 0.6.0 - Remote Code Execution (RCE)",
        "fork": false,
        "created_at": "2024-04-14T04:08:44Z",
        "updated_at": "2024-10-15T02:54:38Z",
        "pushed_at": "2024-04-25T09:14:46Z",
        "stargazers_count": 1,
        "watchers_count": 1,
        "has_discussions": false,
        "forks_count": 1,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "[]",
        "visibility": "public",
        "forks": 1,
        "watchers": 1,
        "score": 0,
        "subscribers_count": 1
    },
    {
        "cve": "CVE-2022-35411",
        "poc_github": true,
        "full_name": "CSpanias/rpc-rce.py",
        "owner_login": "CSpanias",
        "owner_id": 78966278,
        "owner_html_url": "https://github.com/CSpanias",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/78966278?v=4",
        "html_url": "https://github.com/CSpanias/rpc-rce.py",
        "description": "Exploit for CVE-2022-35411 \u2014 Unauthenticated RCE in rpc.py (<= 0.6.0)",
        "fork": false,
        "created_at": "2025-07-28T09:26:14Z",
        "updated_at": "2025-10-26T10:57:43Z",
        "pushed_at": "2025-07-28T09:46:15Z",
        "stargazers_count": 2,
        "watchers_count": 2,
        "has_discussions": false,
        "forks_count": 0,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "[]",
        "visibility": "public",
        "forks": 0,
        "watchers": 2,
        "score": 0,
        "subscribers_count": 0
    }
]